### ISSUE TITLE
Keyboard Lockout

### ISSUE THREAD

**Issue by pandaman09** [wiremod/wire#797] opened 2015-01-23 20:48 UTC
Issue: Player is locked out of the keyboard. You cannot use any keys except ` (console) unless they use a different wire_keyboard or leave the server.

How to reproduce:
Enable synchronous
Bind leave keyboard to Use (e)
Wire "Kick the bastard out of the keyboard" to "InUse"
Use (e) they keyboard

**Comment by titanic4** [comment] 2015-01-23 21:01
Well, I checked the bug with workshop version of Wiremod and I got exactly same results. Maybe the workaround is to not allow the player to bind the keyboard leaving key to key bound to +use or add the delay for the "Kick the bastard out of the keyboard" to at least 1/100th of a second. The exact line for synchronous wire keyboard is here: https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_keyboard/init.lua#L88
It's probably caused by race condition I think.

**Comment by Divran** [comment] 2015-01-23 22:05
merged

**Closed by Divran** 2015-01-23 22:05 UTC
