### ISSUE TITLE
Reduce lua files count

### ISSUE THREAD

**Issue by arduinium** [wiremod/wire#627] opened 2014-04-29 19:51 UTC
We ran into a problem on our server. Wev'e hit the lua file limit, somehow. We DON'T have 2048 lua files in the addons folder, in fact less than 1000, but still we've apparently hit the limit because if I add one more lua file (it doesn't matter what's inside this file), then the Stools list become empty, as well as other problems..

While counting lua files, I've noticed Wiremod is close to 400 lua files. I think It could be reduced to something like 100 or even less, for example by merging every tools/sents of one category (IO, Display, etc) into few files instead of hundreds.

What do you think about it?

**Comment by AbigailBuccaneer** [comment] 2015-01-06 13:48
Duplicate of Facepunch/garrysmod-issues#1058. Something for the Garry's Mod team to deal with, not us.

**Closed by AbigailBuccaneer** 2015-01-06 13:48 UTC
Labels: Enhancement, External compatibility, Question

**Comment by oldmud0** [comment] 2015-01-10 05:29
Or just make some hyper-minified version of Wiremod, Javascript-style. Just squeeze everything into some meaningless string of text.

**Comment by Divran** [comment] 2015-01-10 14:31
Yeah, but it's a lot harder to do than javascript, because Gmod Lua is serverside and clientside, unlike javascript which is only clientside. Also, some files do `if CLIENT then return end`. You'd have to erase all of those from all of wiremod. You have to change A LOT of things before that would work.

**Comment by AbigailBuccaneer** [comment] 2015-01-12 10:06
Also, quite a lot of files have some bizarre loading mechanism around them that means that they need to be in the correct locations - eg. everything in `lua/entities` - which is where a lot of our files are.

**Comment by Divran** [comment] 2015-01-12 10:19
I believe it is possible to load entities from elsewhere. You just have to manually register them using the functions related to getting the list of entities or something

**Comment by AbigailBuccaneer** [comment] 2015-01-12 10:26
Hmm, actually, it looks like you're right - I can't find anything that loads files from the `entities` directory (which is what lead me to suspect that it's not possible, as I think it's all done in C++ code), but [`entities/widget_axis.lua`](https://github.com/garrynewman/garrysmod/blob/4eb9bb19dcfac06007691376ecaf2dbc56efa6b2/garrysmod/lua/entities/widget_axis.lua) does use this to register multiple entities in a file.

**Comment by Divran** [comment] 2015-01-12 13:12
Yes, exactly, that was it: `scripted_ents.Register(...)`
