### ISSUE TITLE
Editor: Parenthesis highlighting fails

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1169] opened 2016-07-03 10:31 UTC
For example:

![Expression 2](https://cloud.githubusercontent.com/assets/9789070/16544900/c1fc4562-4116-11e6-973e-3721ee94769a.png)

![ZSPU](https://cloud.githubusercontent.com/assets/9789070/16544940/c3e8b4c6-4118-11e6-9b11-acf7ed3fe252.png)

![ZCPU](https://cloud.githubusercontent.com/assets/9789070/16544964/efc1bd1c-4119-11e6-92b4-2aeddb32ce69.png)

It seems like it does not ignore strings and comments..
Also, I have noticed that parenthesis highlighting is offsetted by -1 on the first line (see ZSPU and ZCPU images above).

**Comment by AbigailBuccaneer** [comment] 2018-02-02 13:52
Duplicate of #447.

**Closed by AbigailBuccaneer** 2018-02-02 13:52 UTC
Labels: Bug, Text editor
