### ISSUE TITLE
Ranger and model gate

### ISSUE THREAD

**Issue by xCeezyx** [wiremod/wire#1662] opened 2018-05-27 17:04 UTC
When I break an object in the ranger or delete it with prop core the model class stays in the model gate

**Comment by AbigailBuccaneer** [comment] 2018-05-30 14:54
Can you explain what you mean?

I spawned a Wire Ranger entity (`gmod_wire_ranger`) with all its outputs enabled.
I spawned a gate entity (`gmod_wire_gate`) with the "Model" gate from the entity category (`entity_model`).
 I put a breakable prop in front of it, and then broke it with a weapon.
When I broke the prop, all of the outputs correctly reset to their default value.

Are you describing something else, or is this not working for you? Have you tried doing this with no other addons? Various admin mods and prop protection addons have broken things like `EntityRemoved` hooks in the past.

I'm closing this as 'unable to reproduce', but if you respond with more details I'll reopen it.

**Comment by ajrocks33** [comment] 2018-06-22 21:24
I broke it with prop core, not a weapon sorry for a late response. It happens every time

**Comment by ajrocks33** [comment] 2018-06-22 21:35
![untitled](https://user-images.githubusercontent.com/12651151/41800216-7851a2aa-7629-11e8-8f29-3ba7c9beb5ad.png)

**Comment by xCeezyx** [comment] 2018-06-22 21:58
https://www.youtube.com/watch?v=SeKhwKirwTA

**Comment by bigdogmat** [comment] 2018-06-28 01:33
@AbigailBuccaneer The issue appears to be with how and when entities are considered destroyed. When an entity is destroyed its userdata object now returns true when compared to `NULL`. When `TriggerOutput` checks to see if the value changed it just sees that the destroyed entity is equal to the `NULL` constant, so it doesn't trigger.

For whatever reason when it's removed with something like the remover tool the entity continues to exist even after the ranger stops hitting it. Randomly this'll happen when destroying them with weapons however it seems pretty much random.

I was able to test this by using `rawequal`, maybe this would be a good solution? I'm not sure how much it'd change.

I'm sure there are other entities that are subject to this issue.

**Comment by thegrb93** [comment] 2022-05-05 20:58
The problem is when the entity is deleted, it's value stored in the ranger's output becomes NULL, and since the triggeroutput is now also NULL, the triggeroutput gets ignored since the `if NULL~=NULL` is false

**Comment by thegrb93** [comment] 2022-05-05 21:00
The reason it behaves correctly with remover tool is the entity isn't removed for a delay, and the beam is able to pass through the entity before its deleted.

**Closed** 2022-05-07 23:17 UTC
Labels: Bug
