### ISSUE TITLE
E2 editor non-monowidth fonts

### ISSUE THREAD

**Issue by WetDude** [wiremod/wire#1129] opened 2016-05-04 17:02 UTC
E2 editor's caret positions wrongly if you're using non-monowidth fonts.
In example picture 'graphics' caret is in the middle of the row, but **actual** caret  is at the end of it.
Related issue: #824
![screenshot from 2016-05-04 19 45 51](https://cloud.githubusercontent.com/assets/9086408/15021806/735d5018-1231-11e6-9f92-2e1c24b3bce7.png)
(Sorry for my bad English)

**Comment by Divran** [comment] 2016-05-04 17:12
Use mono-spaced fonts.

**Comment by Divran** [comment] 2016-05-04 17:14
Actually let's not say won't fix. @AbigailBuccaneer was planning on looking at it, but never did, it seems.

**Comment by oldmud0** [comment] 2016-05-05 22:22
How is this not a bug? This is clearly unintended behavior.

**Comment by bigdogmat** [comment] 2016-05-05 22:39
> How is this not a bug? This is clearly unintended behavior.

If the editor was never intended to be used with non mono-spaced fonts, then it's not a bug. Making it support them would be an enhancement

**Comment by Divran** [comment] 2016-05-05 22:53
^

**Comment by TomyLobo** [comment] 2016-05-05 23:07
That would be a major overhaul.
We'd have to either
* place each character individually for non-monospace fonts, so they line up again or
* figure out where the character is that we're in and also make sure up/down makes sense

**Comment by Nebual** [comment] 2018-01-21 22:19
I don't think there's much interest in using non-monospace fonts in a code editor, thus I'm going to close this for now.

**Closed by Nebual** 2018-01-21 22:19 UTC
Labels: Enhancement, Text editor
