### ISSUE TITLE
Wire tool and Advanced Wire Tool don't show I/O HUD

### ISSUE THREAD

**Issue by BluetheFox** [wiremod/wire#845] opened 2015-02-25 20:55 UTC
The advanced wiring tool and the Legacy wiring tool do not show the inputs when hovering my crosshair over a wireable component. The wiring works fine and the menu itself appears to also partially work (makes the usual clicking sound when i right click but not when i mouse wheel) But i cannot see the inputs or output HUD.

I have tried all of the following:
* reinstall wiremod
* reinstall all gmod addons
* reinstall gmod itself
* verified integrity of game cache
* delete all addons accept wiremod, making it be the only addon i have

...If theres any information you need please tell me. im not sure what exactly you guys need to know.

**Comment by Divran** [comment] 2015-02-25 20:57
we've had this issue before. It's caused by gmod_drawhelp being set to 0. See https://github.com/wiremod/wire/issues/749

**Comment by AbigailBuccaneer** [comment] 2015-02-25 21:00
This should soon be fixed by Garry's Mod - the fix is present in Git, garrynewman/garrysmod@680666b1ed62b77517d156f8b0ffc35ba34e920f

**Closed** 2015-02-25 21:01 UTC
Labels: Duplicate
