### ISSUE TITLE
Can't link EGP HUD to vehicle

### ISSUE THREAD

**Issue by SpyCrabSteam** [wiremod/wire#1167] opened 2016-07-02 08:21 UTC
Whenever I try linking the EGP HUD to a vehicle, I get a lua error:

````
[ERROR] addons/wire-master/lua/entities/gmod_wire_egp_hud/init.lua:62: attempt to call method 'LinkHUDToVehicle' (a nil value)
  1. LinkEnt - addons/wire-master/lua/entities/gmod_wire_egp_hud/init.lua:62
   2. RightClick - addons/wire-master/lua/wire/tool_loader.lua:528
    3. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:281
````

**Comment by TomyLobo** [comment] 2016-07-02 08:54
that function is defined in [huddraw.lua] (https://github.com/wiremod/wire/blob/b489718b94182a4a6c3a52cf7b7ffb5a49f8b544/lua/entities/gmod_wire_egp_hud/huddraw.lua), which is included at the top of init.lua.

Are you sure you're up-to-date?

**Comment by SpyCrabSteam** [comment] 2016-07-02 09:03
I just downloaded wiremod from github, pretty sure im up to date. I also looked at the file and it is defined there.

**Comment by TomyLobo** [comment] 2016-07-02 10:29
Try the Workshop version

**Comment by SpyCrabSteam** [comment] 2016-07-02 12:12
Nope, didn't fix it.

**Comment by Divran** [comment] 2016-10-01 18:45
Closing because we're unable to reproduce

**Closed by Divran** 2016-10-01 18:45 UTC
Labels: Bug, EGP, Unable to reproduce
