### ISSUE TITLE
gmod_wire_cameracontroller.lua:389: bad argument #1 to 'WriteFloat' (number expected, got function)

### ISSUE THREAD

**Issue by arula555** [wiremod/wire#868] opened 2015-03-15 09:16 UTC
In the latest Workshop version:

```
[Wiremod] lua/entities/gmod_wire_cameracontroller.lua:389: bad argument #1 to 'WriteFloat' (number expected, got function)
  1. WriteFloat - [C]:-1
   2. SendPositions - lua/entities/gmod_wire_cameracontroller.lua:389
    3. SyncSettings - lua/entities/gmod_wire_cameracontroller.lua:405
     4. DisableCam - lua/entities/gmod_wire_cameracontroller.lua:594
      5. ClearEntities - lua/entities/gmod_wire_cameracontroller.lua:848
       6. unknown - lua/entities/gmod_wire_cameracontroller.lua:579

sv: Wire error (Entity [541][gmod_wire_cameracontroller]):
lua/entities/gmod_wire_cameracontroller.lua:389: bad argument #1 to 'WriteFloat' (number expected, got function)
stack traceback:
	[C]: in function 'WriteFloat'
	lua/entities/gmod_wire_cameracontroller.lua:389: in function 'SendPositions'
	lua/entities/gmod_wire_cameracontroller.lua:405: in function 'SyncSettings'
	lua/entities/gmod_wire_cameracontroller.lua:594: in function 'DisableCam'
	lua/entities/gmod_wire_cameracontroller.lua:761: in function <lua/entities/gmod_wire_cameracontroller.lua:758>
	[C]: in function 'xpcall'
	lua/wire/server/wirelib.lua:62: in function 'TriggerInput'
	entities/gmod_wire_expression2/core/wirelink.lua:14: in function <entities/gmod_wire_expression2/core/wirelink.lua:12>
	[C]: in function 'pcall'
	lua/entities/gmod_wire_expression2/core/init.lua:118: in function <lua/entities/gmod_wire_expression2/core/init.lua:112>
	[C]: in function 'pcall'
	lua/entities/gmod_wire_expression2/init.lua:198: in function 'PCallHook'
	lua/entities/gmod_wire_expression2/init.lua:139: in function 'Execute'
	entities/gmod_wire_expression2/core/gametick.lua:38: in function 'v'
	lua/includes/modules/hook.lua:84: in function <lua/includes/modules/hook.lua:67>
```

**Comment by AbigailBuccaneer** [comment] 2015-03-15 11:53
The latest workshop version looks to be [0f56a368](https://github.com/wiremod/wire/blob/0f56a3688152a131479650fa388ec768c2754980/lua/entities/gmod_wire_cameracontroller.lua), and the stacktrace implies that `type(self.Distance) == "function"`.

Try disabling all your other addons. This sounds most like a bug caused by some other addon.

**Comment by Divran** [comment] 2015-03-15 12:42
We've seen this error many times. It's caused by an addon changing the `Distance` variable on other entities.

**Comment by thegrb93** [comment] 2015-03-15 21:56
player.GetByID(1)

**Comment by Divran** [comment] 2015-03-15 22:13
`Entity(1-64)` is exactly the same as `player.GetByID(1-64)`

**Comment by thegrb93** [comment] 2015-03-16 00:19
interesting

**Comment by Divran** [comment] 2015-03-28 16:58
Closing this since it isn't caused by wiremod. Not our fault if other addons decide to break everything

**Closed by Divran** 2015-03-28 16:58 UTC
Labels: Bug
