### ISSUE TITLE
E2: Array can be initialized with blacklisted types/values

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1181] opened 2016-07-11 21:52 UTC
For example (added foreach line):
```
local R = array(array("inner"), gTableSafe(0), table("epic" = "fail"))  # Validation successful
#printTable(R[1, array])  # No such operator: get array[number, array] at line 2, char 13
#foreach (K, V:array = R) { print(K) }  # Table expression (of type 'r') has no indexing operator at line 3, char 1
```

Screenshot:
![image](https://cloud.githubusercontent.com/assets/9789070/16748023/013ddf04-47c2-11e6-872d-df899943539a.png)

Apparently, arguments types that are passed to `array` function are not checked against blacklist.

**Comment by Divran** [comment] 2016-07-11 22:08
yes they are https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/array.lua#L61

**Comment by CaptainPRICE** [comment] 2016-07-11 22:17
@Divran Yes I see that check.
But, why is it allowed to initialize an array with blacklisted types/values... Just nonsense.

**Comment by bigdogmat** [comment] 2016-07-11 22:21
Because there isn't a way to blacklist varargs to only allow certain types

**Comment by Divran** [comment] 2016-07-11 22:41
>@Divran Yes I see that check.
But, why is it allowed to initialize an array with blacklisted types/values... Just nonsense.
It isn't. See that check.

**Comment by CaptainPRICE** [comment] 2016-07-12 05:31
@Divran
> What you mean to ask is "Why isn't this being caught during parsing?"

Yeah.. Realized that by running:
```
local R = array(array("string 1", "string 2"), "index 2", "index 3")
printTable(R)
```

Output:
> 2	=	index 2
> 3	=	index 3

**Comment by TomyLobo** [comment] 2016-07-12 20:31
So since, as you noted, Arrays cannot be initialized with blacklisted types, this issue has evaporated.
Closing...

**Closed by TomyLobo** 2016-07-12 20:31 UTC
Labels: Bug, Can't fix, E2, Invalid, Not a bug, Unable to reproduce, Won't fix

**Comment by oldmud0** [comment] 2016-07-12 20:40
wow, TomyLobo just went full on with the tags.. `Bug` + `Not a bug`. Seems legit.

**Comment by TomyLobo** [comment] 2016-07-15 06:03
It was reproducible?
How?

**Comment by Anticept** [comment] 2016-07-15 07:48
You did go crazy lol.

**Comment by oldmud0** [comment] 2016-07-15 12:48
The code does the same behavior for everyone. It's reproducible.

**Comment by Divran** [comment] 2016-07-15 14:36
@oldmud0  "reproducable" implies that there was a bug, but there isn't one. The correct tags for this is "E2" and "Not a bug".
Optionally "Improvement" if we are going to change the "array" function from a function into a language construct, in which case we should be able to do the type checking during parsing instead of runtime.

Can also optionally add the tag "Won't fix", but that's mostly used when there actually is an issue (not necessarily a bug) that we aren't going to fix.

**Comment by TomyLobo** [comment] 2016-07-15 20:12
a language construct just so we can show security-related errors better? i don't think so

**Comment by oldmud0** [comment] 2016-07-15 22:13
"E2" and "security" don't go in the same sentence.

**Comment by TomyLobo** [comment] 2016-07-16 08:51
you're confusing that with Lua :)

Apart from the obvious lack of memory constraints, E2 security actually does exist.
(or I should say it did exist when I left the project)

You can't just push around random people's props and such

**Comment by Anticept** [comment] 2016-07-18 23:51
@Divran Kk
