### ISSUE TITLE
"Disconnect: Client 3 overflowed reliable channel" from E2 code

### ISSUE THREAD

**Issue by BoggLog** [wiremod/wire#1006] opened 2015-11-04 01:26 UTC
I already issued this and it was already fixed, but now it happens again, printing reliable stream overflow and disconnecting from server.
- I checked this a month ago, but couldn't write here, so writing now, I'm pretty sure it's still there.
  Spawn any e2 sized over 500KB to reproduce.

**Comment by BoggLog** [comment] 2015-11-04 02:28
Wow, sorry for that, it may be actually working, I'll test deeper with exact code and check again

**Comment by immibis** [comment] 2015-11-04 04:20
Why do you have an E2 that's over 500kB?

**Comment by BoggLog** [comment] 2015-11-04 13:40
It's just a little bit complex e2 which I'm writing time to time for about 3 years or so.
But it seems all right for now, so blame me and close this please.

**Comment by AbigailBuccaneer** [comment] 2015-11-06 13:30
From #1007:
> @BoggLog:

>> offtop: my previous issue with uploading big files turned out being actually something other. Probably it's with gtables, and it spams console with something about "sending 256-bytes umsg failed: max is 255" like 15 times and then "User overflowed reliable stream", crashing client and getting to main menu... trying to reproduce that now. May it be just some simple error setting 256 instead of 255 somewhere in gtables code?

> @Divran:

>> The 256 limit sounds like umsg. gtables are all serverside, so they don't use umsg or net messages. The problem is not with gtables.

> @BoggLog:

>> This is weird then\ It happens in a part where I'm just working with gtables, tables, and resetting 4 e2's. It used remoteSetCode, but I disabled that for testig and it stil happens\ Well, we'll see later today

So it looks like there is a genuine problem, just not to do with uploading.

**Comment by BoggLog** [comment] 2015-11-06 17:10
Well, It seem to be caused by printing array of ents...
So, I have a big shared gTable, table inside of it, and there is array of ents. And when I'm trying to print it out with printTable(LinkTo2Layer["some_ents"]), I get this. Though, I still need a further testing, because I tried to reproduce it in separated environment and it worked\. But seems to be somewhere around, because it's the only part connected with umsgs.

**Comment by BoggLog** [comment] 2015-11-06 17:41
Okay. It was not exactly array of ents.
But related to printTable function.
The thing I noticed just now is that it prints a lot of text to console if it's in table's first layer, like
printTable(table("t" = "very long text"))
Probably, that is the problem.
Willl be testing more.

**Comment by arduinium** [comment] 2015-11-07 00:02
You can also reproduce this by printing a string that is over 255 characters.

**Comment by BoggLog** [comment] 2015-11-07 11:29
Hm, I couldn't reproduce it with just trying to print long string (it comes to "not enought memory" and freezes a little, otherwise it prints small part as it should)
But here it is for printTable: http://pastebin.com/gTm9tCks
Tried that on server and it printed
"Disconnect: Client 3 overflowed reliable channel..
Disconnect: Client 3 overflowed reliable channel.."
And disconnected, of course.
So it seems he problem is printTable trying to print whole strings instead of first chars. It actually worked with pretty big strings, actually printing 1k lines or more to console, until it reached some limit.

**Comment by immibis** [comment] 2015-11-07 12:52
@BoggLog What if you just print a table with a long string in it, and nothing else? (`" ":repeat(100000)` or similar)

**Comment by BoggLog** [comment] 2015-11-07 13:00
tried that, and without nesting it worked. I was just experimenting and came to what I posted. I'll try to simplify later today if needed.

**Comment by BoggLog** [comment] 2015-11-09 16:17
@immibis I finally tried as hard as I can and was not able to reproduce that without nesting. It just starts to lag, freeses, comes out of memory with around 4k of that commented lines which is around 1Mb. Sometimes it just freezes for a couple of seconds, and sometimes windows fails with it's "desktop windows manager" (I have russian win, not sure). Anyways. That all is a little bit strange, but probably is all right for now (don't block e2 please... whatever...).

So yes, it needs nesting to be reproduced. And the size of table to reproduce it is around 100.. (128, probably?) Kb.

**Comment by Nebual** [comment] 2018-01-21 10:58
The pastebin has expired, so I'll close this ticket as unreproducable for now.

**Closed by Nebual** 2018-01-21 10:58 UTC
Labels: Bug, E2
