### ISSUE TITLE
Expression 2 editor - highlight copies of selected word fails when occurrences are separated by one character

### ISSUE THREAD

**Issue by revosw** [wiremod/wire#1601] opened 2018-03-13 13:03 UTC
Yet another miniscule one, I'm running revision 4031 (latest as of time of writing)

The words are highlighted only when more than one character, doesn't matter which, separates the last occurrence.

![](https://i.imgur.com/Uvte6W2.png)

**Comment by Matt1923** [comment] 2018-03-13 17:19
This is intended behaviour, the editor intentionally has a check to make sure only whole words are found.
'-- [^a-zA-Z0-9_] ensures we only find whole words, and the gsub escapes any regex command characters that happen to be in str
local pattern = "[^a-zA-Z0-9_]()" .. str:gsub("[%-%^%$%(%)%%%.%[%]%*%+%?]", "%%%1") .. "()[^a-zA-Z0-9_]"`

**Comment by Divran** [comment] 2018-03-13 18:23
could possibly be fixed by stepping back 1 char after finding

**Comment by AbigailBuccaneer** [comment] 2018-03-14 08:36
It's also possible to do this with a *frontier pattern*:

> `%f[set]`, a frontier pattern; such item matches an empty string at any position such that the next character belongs to set and the previous character does not belong to set. The set set is interpreted as previously described. The beginning and the end of the subject are handled as if they were the character `'\0'`.

```Lua
> test = "same.same|same |same|  same//same/same same same same same"
> test:gsub("%f[%a]same%f[%A]", print)
same
same
same
same
same
same
same
same
same
same
same
```

**Comment by Divran** [comment] 2018-03-16 16:44
@AbigailBuccaneer fixit

**Closed** 2018-04-28 00:07 UTC
