### ISSUE TITLE
Error refreshing a file in text editor after it's been renamed

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1235] opened 2016-10-17 19:04 UTC
## Steps to reproduce
1. Create and save a new file via Editor, keep a file opened.
2. Find a file you've created in file hierarchy (on the left side), and right click it, and then click `Rename to..`.
3. Rename a file to something else.
4. Press the `Refresh file` button.
## Details

When a file is renamed, the editor doesn't seem to update the underlying filename for the opened file.
For example, the following script error is thrown:

Console output:

> Erroring opening file: expression2/new-filename.txt

There is a typo in there (Erroring). I have also noticed that there is no stack trace, and no line break at the end of the error message.

**Comment by Divran** [comment] 2016-11-12 20:13
How did you get that error message? I tested it just now, and got no error. I renamed the file while having that file opened in a tab, and I was able to use that tab just fine. When I saved that tab I had opened, however, it saved it as the old file path (which is fine and could be considered intended behavior, since this is how most editors handle this, like for example sublime text 3).

**Comment by TomyLobo** [comment] 2016-11-28 09:24
A git branch is very light-weight. Don't be afraid to create one, even if it's just for showing things.
It's easier to see a diff of what you actually changed that way

**Comment by AbigailBuccaneer** [comment] 2018-02-02 14:01
This might have been fixed by #1524.

**Comment by CaptainPRICE** [comment] 2019-04-22 03:18
> This might have been fixed by #1524.

I just went to test it (Wiremod's version: 'Git bbb1f50'), and that would be a no.
This is still a bug.

**Closed** 2019-06-10 21:37 UTC
Labels: Bug, Text editor
