### ISSUE TITLE
E2 Duplicator-support inconsistency

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1407] opened 2017-06-22 18:57 UTC
Ok. Let's explain it.

## Test E2
```golo
print("first=" + first() + ", duped=" + duped() + ", dupefinished=" + dupefinished())
```

## Description
`first()` will always return `1` (true) only if you spawn/upload it with Expression 2 STool⁽¹⁾.
`first()` will always return `0` (false) when pasted no matter which duplicator STool is used.

It is a bit more complicated to explain the rest. So here are the results...

When you spawn/upload Test E2 with Expression 2 STool⁽¹⁾, the chip will **run only once** and produce the following output:
```
first=1, duped=0, dupefinished=0
```

When you paste the Test E2 with Garry's Duplicator STool, the chip will **run only once** and produce the following output:
```
first=0, duped=1, dupefinished=0
```

When you paste the Test E2 with Wire Advanced Duplicator STool, the chip will **run twice** and produce the following output:
```
first=0, duped=1, dupefinished=0
first=0, duped=0, dupefinished=1
```

See the problem. Inconsistency.
I see a solution to this problem; either change `first()`-or-`dupefinished()` function to return `1` (true) when it is pasted with Garry's Duplicator STool and make `duped()` function return `0` (false) instead. So that when you would paste the Test E2 with Garry's Duplicator STool, the chip would still **run only once** but produce the following output:
```
first=1, duped=0, dupefinished=0
```
-or-
```
first=0, duped=0, dupefinished=1
```

This change would mean we can finally have such E2 work for **all duplicator STools**, consistently:
```golo
if (first() | dupefinished()) {
    #[ ... ]#
}
```

### References
⁽¹⁾ — Or use Remote Updater feature, or use `remoteupload` extension, or alike

[`first()`](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/core.lua#L287-L289)
[`duped()`](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/core.lua#L291-L293)
[`dupefinished()`](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/core.lua#L326-L339)
[Garry's Duplicator STool](https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/stools/duplicator.lua)
[Wire AdvDupe2](https://github.com/wiremod/advdupe2)

**Comment by AbigailBuccaneer** [comment] 2017-06-22 19:35
As I'm sure you're aware, the point of `duped` is that it fires when the E2 chip itself is pasted, and `dupefinished` fires when the entire contraption has finished pasting - which is information that (as far as I'm aware) isn't possible to get from Garry's standard duplicator. (If you have read the code and know a way, feel free to open a pull request!)

For all intents and purposes, `if (first() | duped())` is the cross-tool way of having a block of code execute on first run only. `dupefinished()` is only there for large contraptions that are pasted slowly - if you need to use it, you'll already have discovered the problems with delayed duping that make it necessary, and you'll already be familiar with the behaviours of different duplicators.

I don't like the fact that it runs twice though. If I were implementing the API, I'd have stuck with `first()` and `duped()` only - and delayed `duped()` for advdupe until the entire contraption is pasted.

**Comment by CaptainPRICE** [comment] 2017-06-22 19:43
> I don't like the fact that it runs twice though. If I were implementing the API, I'd have stuck with first()  and duped() only - and delayed duped() for advdupe until the entire contraption is pasted.

That's pretty much the problem. So, either we change it that way, or the way I have described in the OP.
There are two solutions now.

**Comment by adosikas** [comment] 2017-06-22 22:43
I made a test E2, spawned it and duped it in singleplayer with garrydupe, advdupe 1 and advdupe 2:

```
@persist A
runOnTick(1)
if(tickClk()){A++}
if(first()|duped()|dupefinished()){
  print(A+": "+first()+"/"+duped()+"/"+dupefinished())
}
```

Print | Trigger 
---|---
0: 1/0/0  |   Spawning
535: 0/1/0   | Paste with GarryDupe
692: 0/1/0   | AdvDupe Paste Start
692: 0/0/1   | AdvDupe Paste Done
1148: 0/1/0   | AdvDupe2 Paste Start
1149: 0/0/1 |   AdvDupe2 Paste Done

(delay between start and done gets bigger with more props)

That is exactly what I expect the functions to do, given their documentation:

Function | E2Helper and Wiki documentation 
---|---
first() | Returns 1 if the expression was spawned or reset
duped() | Returns 1 if the expression was duplicated
dupefinished() | Returns 1 when the contraption has finished duping. (Only triggers on Adv Duplicator, not the normal duplicator)

(The description for dupefinished should be adjusted to include advdupe2 though)

---

And besides, how would one even go about "fixing this".

For reference, [garrydupe calls](https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/modules/duplicator.lua#L765) (after *everything* has been pasted) [this in the baseclass](https://github.com/wiremod/wire/blob/master/lua/entities/base_wire_entity.lua#L399) which calls [this](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/init.lua#L489), and AdvDupe2 does the same [here](https://github.com/wiremod/advdupe2/blob/master/lua/advdupe2/sv_clipboard.lua#L1013) (after all enties are spawned, but before constraints, dupe1 is similar).

AdvDupe 1 and 2 also call [this hook](https://github.com/wiremod/advdupe2/blob/master/lua/advdupe2/sv_clipboard.lua#L1051), garrydupe doesn't.

---

I recommend renaming this to `Gmod Duplicator doesn't trigger dupefinished()` and closing this as [Not a bug] and/or [Can't fix].  
When relying on things from a dupe you should check for those before you start anyway.

**Comment by Nebual** [comment] 2018-01-19 11:57
@adosikas Thank you for the VERY detailed research, reproduction E2, and clear description! #1515 should address this.

**Closed** 2018-02-01 08:48 UTC
Labels: E2
