### ISSUE TITLE
E2 array outputs don't update when written to unless chip is reset (manually)

### ISSUE THREAD

**Issue by Andrew-Eathan** [wiremod/wire#1725] opened 2018-09-18 18:34 UTC
I've noticed this bug many times before, and it seems it still persists so i decided to add a issue here.
Apparently, when pasting a contraption via either duplicator or advdupe2, the E2s in that specific contraption won't write to output arrays at all unless i manually reset or re-upload the chip.

**Comment by thegrb93** [comment] 2018-09-18 19:05
Maybe fixed by https://github.com/wiremod/wire/pull/1724/files

**Comment by Andrew-Eathan** [comment] 2018-09-19 09:56
you mean the bug is fixed? i might do a re-test later and see if it works

**Comment by thegrb93** [comment] 2018-09-19 13:11
No

**Comment by Andrew-Eathan** [comment] 2018-09-19 16:10
oh.

**Comment by Andrew-Eathan** [comment] 2018-11-30 18:45
similar to #1611

**Comment by thegrb93** [comment] 2022-02-25 02:49
Yeah this is a duplicate of that

**Closed by thegrb93** 2022-02-25 02:49 UTC
Labels: Bug, Duplicate, E2
