### ISSUE TITLE
DarkRP 2.5 wire rangers spawning as world props

### ISSUE THREAD

**Issue by sovietfred** [wiremod/wire#1079] opened 2016-01-11 03:40 UTC
I have wire and wire extras set to automatically update to the SVN version daily so I should have the latest version already. For all of my players on my darkrp server, the rangers spawn as world props so only admins can interact with them. A few weeks ago this wasn't an issue and the rangers would spawn as a player owned entity and nothing else in wire seems to be affected in the same manner. We're using falco's prop protection if it matters.

**Comment by bigdogmat** [comment] 2016-01-11 05:02
Nothing has changed with rangers for 4 months, so this isn't a wiremod issue. Try reinstalling wiremod and or reinstalling fpp, as your svn auto-updater could have corrupted one of them. If that doesn't work then try making a issue on the fpp github.

**Comment by AbigailBuccaneer** [comment] 2016-01-11 10:33
For what it's worth, SVN is a deprecated method of getting the latest code - it'd be preferable if you were using git, so you could tell us which git revision is causing this (as otherwise we have to just assume that your SVN updating works okay etc.) As @bigdogmat has pointed out that it may be because of a corrupted Wiremod checkout, now's a good time to delete the SVN version and get it via git instead. Join us in the future! :smile:

@bigdogmat is right - neither the ranger code, the ranger tool code nor the `WireLib.MakeWireEnt` code has changed for months.

By "world props" do you mean a `gmod_prop`, or just a `gmod_wire_ranger` that doesn't belong to any player? If it's the latter (you say admins can interact with them, I'm not sure if you mean admins can wire them or not) then it's most likely a problem with FPP.

**Comment by TomyLobo** [comment] 2016-01-11 23:11
shouldn't we treat this as a darkrp bug until it has been reproduced without darkrp?

**Comment by oldmud0** [comment] 2016-01-12 02:55
Why was this tagged as bug? We don't even know if it's a Wire bug, a DarkRP bug, or an FPP bug.

**Comment by bigdogmat** [comment] 2016-01-12 03:03
I'm gonna bet SVN corrupted the Wiremod install, mainly because I've never heard of FPP doing something like this unless they did something wrong in the settings. Also when I did use SVN I remember it corrupted half the shit I checked out.

**Comment by AbigailBuccaneer** [comment] 2016-01-12 09:50
> Why was this tagged as bug? We don't even know if it's a Wire bug, a DarkRP bug, or an FPP bug.

Because in any of those situations it's still a bug. 'Bug' doesn't mean 'Bug in our software', and we can still close it later as invalid / unable to reproduce.

**Comment by TomyLobo** [comment] 2016-01-12 17:05
Git is like the savant that has trouble interacting with people but never forgets anything and never makes mistakes.
SVN is like an infant that falls over all the time, needing "clean-up".

**Comment by sovietfred** [comment] 2016-01-16 04:19
I'll try switching to the git and see if that fixes it.

**Comment by AbigailBuccaneer** [comment] 2016-01-16 13:08
If you still have problems, try with no other addons, and find out which addons are conflicting. Then go blame them :wink:

**Closed** 2016-01-16 13:07 UTC
Labels: Bug, Unable to reproduce

**Comment by abforme2005** [comment] 2017-12-30 14:42
I am having the same issue with the wire_ranger changing to world prop.  Wire_ranger changes to world and is preventing it from being removed or moved by users.

**Comment by sovietfred** [comment] 2018-01-04 04:24
I wasn't able to find a fix, my server closed a while ago. Sorry Abforme.
