### ISSUE TITLE
Proposal for an anti "Limit hit" spam

### ISSUE THREAD

**Issue by Guillaume57** [wiremod/wire#834] opened 2015-02-17 08:11 UTC
I was spawning a lot of props with an E2, suddently I reached the prop limit and it lagged me like never before, with like hundreds of loud "You've hit the Prop limit" hints all at once.

So I did something about it and propose to include it, in prop.lua

```
local meta = FindMetaTable( "Player" )
meta._LimitHit = meta._LimitHit or meta.LimitHit

function meta:LimitHit( name )
    if CurTime() - (self.PrevLimitHitCheck or 0) >= 5 then
        self.PrevLimitHitCheck = CurTime()
        self:_LimitHit( name )
    end
end
```

What do you think about this?

**Comment by Divran** [comment] 2015-02-17 08:30
The correct solution is to use `propCanCreate()` in your E2.

**Comment by arduinium** [comment] 2015-02-17 08:39
I use propCanCreate, that doesn't stop the spam

**Comment by Divran** [comment] 2015-02-17 08:59
For reference: https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/custom/prop.lua#L24

In that case, that should be fixed. Until then, you can check if the prop returned is valid, and if it isn't stop spawning. Like so
```
local Prop = propSpawn(...)
if (!Prop) {
    Stop spawning here
} else {
    keep spawning more
}
```

**Comment by AbigailBuccaneer** [comment] 2015-02-17 09:19
I'm with @Divran on this - the real issue is seemingly that `propCanCreate` is broken.

**Comment by Divran** [comment] 2015-02-17 09:55
Pretty sure the problem occurs when the prop limit is lower than the E2 propSpawn prop limit.

**Comment by arduinium** [comment] 2015-02-17 10:21
Of course.

I have an idea about an additional function `propCanSpawn( model )`, that would temporarily disable the "You've hit the prop limit' hints and then return the value of `gamemode.Call( "PlayerSpawnProp", self.player, model )`. And of course, same thing with a `seatCanSpawn( model )`. That would also solve a problem with restrictions addons such as URS.

What do you think? I'll look into it.

**Comment by Divran** [comment] 2015-02-17 10:39
propCanSpawn already shouldn't cause any hints to be printed.

**Comment by thegrb93** [comment] 2015-02-17 19:39
propCanSpawn isn't creating the hints, the problem is he's relying on it to know whether or not he can spawn a prop, which it says he can even if he's hit the max props. propCanSpawn should check the number of spawned props against the sbox_maxprops and sbox_maxwire_props.

**Comment by arduinium** [comment] 2015-02-17 20:15
No it should call the `PlayerSpawnProp` gm hook, that's what prop restriction scripts (well, at least URS, I don't know of any others anyway) use to restrict. Hence, the need of an additional function with a `model` parameter, because URS can restrict props per model, as well as per count. As said, this function should temporarily disable the "Limit Hit" hints in case the hook return false.

**Closed** 2018-11-25 02:01 UTC
Labels: E2, Enhancement, Solution/PR pending
