### ISSUE TITLE
Editor code folding

### ISSUE THREAD

**Issue by oldmud0** [wiremod/wire#876] opened 2015-03-22 14:26 UTC
That would be cool for ostensibly long comments or functions. Unfortunately I have no experience working with the Wire codebase.

**Comment by AbigailBuccaneer** [comment] 2015-03-23 10:31
Duplicate of #754.

**Closed by AbigailBuccaneer** 2015-03-23 10:31 UTC
Labels: E2, Enhancement

**Comment by Divran** [comment] 2015-03-23 10:36
It's true that this is a duplicate of that issue thread, but no one answered this question in that issue thread. I'd just like to point out that I have worked a little bit on this, but I never finished it and I don't think I will. The E2 editor just doesn't support it very well, so it's too much work for too little gain.

**Comment by AbigailBuccaneer** [comment] 2015-03-23 10:37
Isn't it worth saying that on the bug that's still open? :P

**Comment by Divran** [comment] 2015-03-23 11:21
yeah but that one is old, idk
