### ISSUE TITLE
E2 'setToolMenuIcon' Lua error upon anyone joining.

### ISSUE THREAD

**Issue by rokex** [wiremod/wire#1127] opened 2016-05-03 23:30 UTC
Whenever somebody joins my DarkRP server this error shows up in the console
```lua
[ERROR] lua/wire/stools/expression2.lua:11: attempt to call field 'setToolMenuIcon' (a nil value)
  1. unknown - lua/wire/stools/expression2.lua:11
   2. include - [C]:-1
    3. LoadTools - addons/wire/lua/wire/tool_loader.lua:6
     4. unknown - addons/wire/lua/wire/tool_loader.lua:573
      5. include - [C]:-1
       6. unknown - addons/wire/lua/weapons/gmod_tool/stools/wire.lua:6
        7. include - [C]:-1
         8. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/stool.lua:142
          9. include - [C]:-1
           10. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:363
            11. include - [C]:-1
             12. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/cl_init.lua:10
```
Is this a common problem?
Any help is appreciated.

**Comment by oldmud0** [comment] 2016-05-04 01:57
Seems like it's due to an inherent lack of tool menu. Bad DarkRP config maybe?

**Comment by Divran** [comment] 2016-05-04 06:55
This error appears when this function:
https://github.com/wiremod/wire/blob/master/lua/wire/tool_loader.lua#L422-L426
doesn't exist. As you can see, this function is created in wiremod's
tool_loader.lua file. The only way I can see this happening is if you have
the latest version of E2 installed, while at the same time, your
tool_loader.lua is somehow an old version.

**Comment by Divran** [comment] 2016-06-11 13:58
Closing because we can't reproduce, and the OP has vanished.

**Closed** 2016-06-11 13:58 UTC
Labels: Bug, Unable to reproduce
