### ISSUE TITLE
Expression 2 Cvars Not Replicating

### ISSUE THREAD

**Issue by MuteTM** [wiremod/wire#616] opened 2014-04-14 18:16 UTC
As the title says, the expression2 cvars don't seem to be replicating correctly after I updated wire this morning. I only have one server to test this on, so I'm not 100% sure it's not an issue on my end (apologies in that case).

```
] wire_expression2_quotahard
"wire_expression2_quotahard" = "100000" ( def. "" )
 replicated server_can_execute clientcmd_can_execute

] rcon wire_expression2_quotahard
"wire_expression2_quotahard" = "25000" ( def. "" )
 game replicated clientcmd_can_execute
```

![Imgur](http://i.imgur.com/dFaoK2D.png)
This chip is limited by perf, the client sees it as taking 10% of the quota.

**Comment by Jack37** [comment] 2015-01-11 09:05
This is still happening, tbh I have no idea why.

**Comment by AbigailBuccaneer** [comment] 2018-01-29 21:36
I still can't reproduce this. Can anybody, and if so, how? I would've thought we'd have seen more reports of this if it was still an issue. Closing until anybody can give me some evidence it's still happening, I'll happily reopen if that happens.

**Closed by AbigailBuccaneer** 2018-01-29 21:36 UTC
Labels: Bug
