### ISSUE TITLE
E2: Hologram "attempts to perform arithmetic on a nil value".

### ISSUE THREAD

**Issue by mozi-h** [wiremod/wire#1454] opened 2017-08-11 01:26 UTC
I thought of making an E2 that defibrilates players: https://pastebin.com/5LBi2GGu
But every time I revive someone they get spawned but aren't teleported (See lines 38-95 and 113-137) . A Lua error breaks the E2's execution and prints the following into the console:
`sv: Expression 2 (Defibrilator): entities/gmod_wire_expression2/core/hologram.lua:490: attempt to perform arithmetic on local 'index' (a nil value)` 
So I looked up, what line 490 in hologram.lua does - it handles the createHolo() function. (https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/hologram.lua)
I commented everything that uses holos out and tested it over and over again. Never works. If not correct me, but I suspect it to be broken on your side.

**Comment by Codingale** [comment] 2017-08-11 03:41
Can't reproduce.

**Comment by CaptainPRICE** [comment] 2017-08-11 07:31
@mozi-h 
Please update your server's Wiremod to use the newest git `master` branch version (and sanitize your Workshop addons appropriately, that is, unsubscribe Wiremod or remove Wiremod from your server's content collection). So, there won't be any conflicts, and you will be using git version.
Above work is required on your side, once you do it, then please check it again, and if you are still able to reproduce the exact issue in your singleplayer, tell us more details and the steps. Otherwise, I am voting to close this as "invalid" (or "outdated"), because I am also unable to reproduce the issue you have described.

**Comment by Codingale** [comment] 2017-08-11 14:54
Fun fact we're on the same server.

**Comment by mozi-h** [comment] 2017-08-11 18:20
I couldn't test it on a freshly updated dedicated for some reasons, but ran into the line that causes the error: Line number *drummroll please* 91!
Aparently I can't delete the indicators in the same execution of the chip when I'm attempting to revive someone. I just delayed it with a timer() and it works now. Still have no clue why tho.
This robbed about 3 hours of my day. Wow.

**Comment by CaptainPRICE** [comment] 2017-08-12 17:12
@mozi-h You can close it yourself.

**Closed** 2017-08-21 14:54 UTC
