### ISSUE TITLE
array:minIndex/maxIndex() does not work correctly with non-numbers?

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1137] opened 2016-06-06 18:07 UTC
[e2function number array:minIndex()](https://github.com/wiremod/wire/blob/c25f642c3bec03261b2ba7354000f21fdd3bb095/lua/entities/gmod_wire_expression2/core/array.lua#L406)
[e2function number array:maxIndex()](https://github.com/wiremod/wire/blob/c25f642c3bec03261b2ba7354000f21fdd3bb095/lua/entities/gmod_wire_expression2/core/array.lua#L446)
```
local R1 = array("1", "2", "3", "4")
print("(R1):  Count=" + R1:count() + ",  MinIndex=" + R1:minIndex() + ",  MaxIndex=" + R1:maxIndex() + ",  Min=" + R1:min() + ",  Max=" + R1:max())

local R2 = array(1 = "First", 2 = "Second", 3 = "Third", 4 = "Fourth")
print("(R2):  Count=" + R2:count() + ",  MinIndex=" + R2:minIndex() + ",  MaxIndex=" + R2:maxIndex() + ",  Min=" + R2:min() + ",  Max=" + R2:max())
```

Output:
> (R1):  Count=4,  MinIndex=1,  MaxIndex=4,  Min=1,  Max=4
> (R2):  Count=4,  MinIndex=1,  MaxIndex=1,  Min=0,  Max=0

Shouldn't `R2:maxIndex()` return the same number as `R1:maxIndex()`?
Both of them are in sequential order, 1-4.

Also, how would you loop through a bit more tedious array, using a for-loop?
```
local R3 = array(0 = "Null", 1 = "Number One", 5 = "High Five", 101 = "Binary")
```
I have tried to find a function which would return an array of indexes of an array, but I haven't found it (much like `array=table:keys()` function, but for array).

**Comment by bigdogmat** [comment] 2016-06-06 20:14
> Also, how would you loop through a bit more tedious array, using a for-loop?
> 
> local R3 = array(0 = "Null", 1 = "Number One", 5 = "High Five", 101 = "Binary")
> I have tried to find a function which would return an array of indexes of an array, but I haven't found it (much like array=table:keys() function, but for array).

Use a foreach loop,

```
foreach(K, V:type = Array){}
```

As for the issue at hand, there are a few issues with both functions. 

For some reason [minIndex doesn't use the tonumber converted value](https://github.com/wiremod/wire/blob/c25f642c3bec03261b2ba7354000f21fdd3bb095/lua/entities/gmod_wire_expression2/core/array.lua#L412) and instead uses the default value returned in the array. Your second array should return 0 for the minIndex because those aren't valid numbers, but because of the mistake I pointed out above, it's comparing them by ascii values. This could cause an error if you had an array with number values and string values, as it'd try to compare them

The reason maxIndex is returning 1 is because of the tonumber behavior we're doing. For the first index the index variable is set to it no matter what, this is because no matter the value it's going to be converted to 0. So if I had it guess it's random luck that the pairs loop just happened to go through the first index in the array first.

**Comment by CaptainPRICE** [comment] 2016-06-06 21:51
@bigdogmat

> Use a foreach loop,
> foreach(K, V:type = Array){}

Nope. That would be _cheating_ in my situation (as why I said using a for-loop), and also foreach is broken in debug mode atm...

> Also it seems you're confused by what the functions are meant to do. They're meant to return the index of the lowest, or highest number in the array, not return the highest, or lowest index

Yeah.. I understand that part now (docs have confused me "Returns the index of the smallest value in the array").

So, in any way, if somebody could add a function (like `array=array:indexes()`) then it would be possible to do it using a for-loop..

**Comment by bigdogmat** [comment] 2016-06-06 21:55
> So, in any way, if somebody could add a function (like array=array:indexes()) then it would be possible to do it using a for-loop..

I thought that was fixed, unless the pr hasn't been merged yet. Either way there is a way, you just can't use it because you're in debug mode, though I don't understand why, foreach loops are better in almost all situations.

**Comment by Divran** [comment] 2016-06-06 21:56
The correct way to iterate such arrays is using a foreach loop. However if you want to be stubborn and do it in a terribly inefficient way, then go ahead and convert your array into a table and then fetch its indexes.

**Comment by TomyLobo** [comment] 2016-06-06 21:58
talk about terribly inefficient... why are you using debug mode while not developing extensions?

also, i thought that was fixed already

**Comment by CaptainPRICE** [comment] 2016-06-06 22:21
@TomyLobo Whoops, my mistake I have forgot to sync Wiremod addon... Yep, okay foreach-loop in debug has been fixed, nice.

**Comment by Divran** [comment] 2016-06-07 06:54
You replace `@persist R:array` with `@persist R:table` and you're done

**Comment by CaptainPRICE** [comment] 2016-06-07 10:23
@Divran
That's also a nope, because I have to work via array - not table. Because, I don't have access to an external E2 (working with datasignals).

**Comment by bigdogmat** [comment] 2016-06-07 11:34
> If there is no other way than using a foreach-loop, then the following is false

Well I mean, arrays in E2 aren't meant to be unsequential by design considering by design they use default Lua arrays.

**Comment by Divran** [comment] 2016-06-07 11:47
It would be possible to add `array:indexes()` but I see no reason to. The only reason tables have it is because 1) they were added was before foreach loops existed, and 2) because E2 tables are meant to be able to be used with non-sequential keys.

>If there is no other way than using a foreach-loop, then the following is false (from Expression 2 wiki):

lol
you're just being limited by this other E2 that you say you don't have access to. Blame them for writing bad code.

>Well I mean, arrays in E2 aren't meant to be unsequential by design: considering they use default Lua arrays.

Lua doesn't have arrays, only tables, and Lua tables were designed to work for everything. E2 just uses Lua tables to implement arrays (which work best as sequential arrays, but you're not forced to do so), and tables (which are more similar to Lua's tables in the sense that they work for everything - however, E2 tables are a teeny tiny bit slower than E2 arrays due to some additional overhead) completely differently.

**Comment by bigdogmat** [comment] 2016-06-07 11:52
> Lua doesn't have arrays, only tables, and Lua tables were designed to work for everything. E2 just uses Lua tables to implement arrays (which work best as sequential arrays, but you're not forced to do so), and tables (which are more similar to Lua's tables in the sense that they work for everything - however, E2 tables are a teeny tiny bit slower than E2 arrays due to some additional overhead) completely differently.

I didn't meant that if you used an unsequential array within Lua you're limit because of how the default table functions worked. Also I said Lua arrays because of how the array part is handled differently from the string indexed part.

**Closed** 2016-06-11 13:58 UTC
