### ISSUE TITLE
[ERROR] entities/gmod_wire_expression2/core/table.lua:84: bad argument #2 to '?'

### ISSUE THREAD

**Issue by Mista-Tea** [wiremod/wire#912] opened 2015-06-13 09:36 UTC
I hate to just come here and paste you an error stack trace but I figured reporting it would be better than nothing. Just noticed this occur on my server console. I don't have any context or way to replicate, sorry.

~~(Sorry about the autolink to issue # 2)~~

```
[ERROR] entities/gmod_wire_expression2/core/table.lua:84: bad argument #2 to '?' (number expected, got nil)
  1. unknown - [C]:-1
   2. temp - entities/gmod_wire_expression2/core/table.lua:84
    3. unknown - entities/gmod_wire_expression2/core/table.lua:108
     4. unknown - addons/wire/lua/weapons/gmod_tool/stools/wire_debugger.lua:226

Timer Failed! [Wire_DebuggerThink][@addons/wire/lua/weapons/gmod_tool/stools/wire_debugger.lua (line 255)]
```

code refs:
[table.lua:84](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/table.lua#L84)
[table.lua:108](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/table.lua#L108)
[wire_debugger.lua:226](https://github.com/wiremod/wire/blob/master/lua/weapons/gmod_tool/stools/wire_debugger.lua#L226)

**Comment by TomyLobo** [comment] 2015-06-13 20:58
If this is what it looks like, there probably isn't much to do about it without being able to reproduce the issue.
To me this looks like something is storing a nil in some field that is marked as numeric.
The wire debugger happens to stumble upon this but the actual problem occurs entirely elsewhere and the only way to obtain an indication would be to reproduce the problem while the "wire_expression2_debug" variable is set to 1.
I would advise against using that feature in regular operation, because it slows down the server a lot.

**Closed** 2018-01-21 11:25 UTC
Labels: Bug, E2
