### ISSUE TITLE
Wiremod Console Commands Are Non-Existent

### ISSUE THREAD

**Issue by HeyLookItsBlu** [wiremod/wire#1402] opened 2017-06-19 04:23 UTC
Hello. My name is Blu and I am a server owner. I've recently encountered a issue with Wiremod. Certain commands such as "wire_holograms_modelany 1" is not being read as an actual command. I have Wiremod and Wiremod Extras installed and alot of the Wiremod cores (I think all the cores)

**Comment by oldmud0** [comment] 2017-06-19 15:06
What extensions do you have enabled?

**Comment by HeyLookItsBlu** [comment] 2017-06-19 15:25
DamageCore, PlyCore, SentCore, and Holo Phys Core.

**Comment by deathking61** [comment] 2017-10-02 22:56
if you have ULX installed try tunning those though the RCON that helps a lot of the time.

**Comment by deathking61** [comment] 2017-10-02 22:57
and besides that DamageCore is actually broken right now as when you try to target a player it gives out errors and then kills the e2.

**Comment by Nebual** [comment] 2018-01-21 03:21
Duplicate of #1470, also need more reproduction steps

**Closed by Nebual** 2018-01-21 03:21 UTC
