### ISSUE TITLE
String concatenation has much too low an op cost

### ISSUE THREAD

**Issue by thegrb93** [wiremod/wire#1051] opened 2015-12-12 10:30 UTC
![string cat](http://swiftbomb.com/wp-content/uploads/2014/12/String.jpg)
can we put a byte limit on the string cat function?

**Comment by MStruntze** [comment] 2015-12-13 01:57
You can do a similar thing with tables.

**Comment by oldmud0** [comment] 2015-12-13 03:15
You can do a similar thing with... well, anything for that matter.

**Comment by CaptainPRICE** [comment] 2016-01-13 04:40
It is also possible to crash any server using nothing else than a simple single statement, print function call... (I think) it exists for very very long period. Because whoever was doing character escaping, failed so hard.

**Comment by AbigailBuccaneer** [comment] 2016-01-13 10:07
@CaptainPRICE please file a new issue with an example.

**Comment by Nebual** [comment] 2018-01-21 11:20
Given that this ticket has no examples anymore, I'm closing it as a duplicate of #887

**Closed by Nebual** 2018-01-21 11:20 UTC
Labels: Bug, E2
