### ISSUE TITLE
Wire Value -- net.lua:182: net.ReadType: Couldn't read type 18

### ISSUE THREAD

**Issue by SlipwayServers** [wiremod/wire#1445] opened 2017-07-31 03:07 UTC
```
[ERROR] lua/includes/extensions/net.lua:182: net.ReadType: Couldn't read type 18
  1. error - [C]:-1
   2. ReadType - lua/includes/extensions/net.lua:182
    3. ReadTable - lua/includes/extensions/net.lua:121
     4. func - addons/t-wire-master/lua/wire/stools/value.lua:22
      5. unknown - lua/includes/extensions/net.lua:32
```

Hello,

This has been spammed hard on my server with both the latest wiremod, and one I was using prior to this version. The server will spike for 10-15 seconds and the webconsole is flooded with this to the point is becomes unresponsive and needs to be refreshed. The last console.log was 180MB. It's extremely random, it has not happened for 10 hours, then it will do it for an hour on and off. Other times it will start doing it shortly after a reboot. Sometimes it will do it for 10 minutes on and off. While it's happening the spike appears every approximately 40-45 seconds.

I have also seen the same issue yesterday but the func was the wire friendlist. Unfortunately I don't have an actual log of that saved. The spam is extremely fast, likely at the rate of think.

It was not doing this a few days ago.

Any advice or assistance would be greatly appreciated. 

value.lua:

```
if SERVER then
	local playerValues = {}
	util.AddNetworkString( "wire_value_values" )
	net.Receive( "wire_value_values", function( length, ply )
		playerValues[ply] = net.ReadTable() -- <<<<< THIS IS LINE 22
	end)
	function TOOL:GetConVars() 
		return playerValues[self:GetOwner()] or {}
	end

	function TOOL:RightClick(trace)
		if not IsValid(trace.Entity) or trace.Entity:GetClass() != "gmod_wire_value" then return false end
		playerValues[self:GetOwner()] = trace.Entity.value
		net.Start("wire_value_values")
			net.WriteTable(trace.Entity.value)
		net.Send(self:GetOwner())
	end
end
```

**Comment by Divran** [comment] 2017-07-31 06:57
This error appears to be caused by the "right click to copy" feature of both the constant value and the friendslist tools. Try right clicking with those tools to see if that reproduces the error.

**Comment by SlipwayServers** [comment] 2017-07-31 13:31
Could a check be added?

I ran the server without wiremod today and it survived  a 12 hours session with not a single lag spike or error. I'm concerned it's a dupe (we have well over 10,000) of one of our players, and being so busy, it's hard to replicate on the live server and dirturbs players.

Is there any chance a check can be added somehow on the send then? It's certainly an odd error, we've been using wiremod on several servers for years.

**Comment by Divran** [comment] 2017-07-31 14:34
To help find the cause of this error, could you change the `SendUpdate` function found inside the `lua/wire/stools/value.lua` file to this
```Lua
	-- Sends the values to the server
	function SendUpdate()
		local old = error
		local err = false
		error = function() err = true end
		
		net.Start("wire_value_values")
			net.WriteTable(selectedValues)
		net.SendToServer()

		error = old
		if err then
			print("An error would have occurred now. This is the data that was sent:")
			PrintTable(selectedValues)
		end
		
		saveValues()
	end
```

**Comment by Divran** [comment] 2017-08-01 18:45
@Python1320 helped me out
```
12:09 AM - Python1320: overfull table
12:09 AM - Python1320: should check if table is full before sending
```
so I've got to add some checks here to make sure they're not sending too much data

**Comment by SlipwayServers** [comment] 2017-08-05 06:23
Yeah I've had the code you suggested in place but the issue seems to have subsided naturally.

Ultimately, if it's an issue that can be address at your end still, so be it.

Cheers for the help.

**Comment by Divran** [comment] 2017-08-05 12:39
@SlipwayServers it's fixed now

**Closed** 2017-08-05 12:39 UTC
