### ISSUE TITLE
SPU Sound Issues

### ISSUE THREAD

**Issue by h3xcat** [wiremod/wire#795] opened 2015-01-23 06:02 UTC
For some reason SPU won't play all notes if you stand from specific angle.
### Video

http://bit.ly/1yQ833x

---

I didn't want to reveal my midi parser code so I wrote memory to file and created new e2 code to read the dump.
### SPU Code

```
// Setup
// Code
reset:
    wset 0,trackwave;
    timer #startTime;
    mov #nextTime, 0;

    mov #memPos, 501;
    mov eax, #memPos;
    mov nextTime, [eax];


    mov  ecx, 32;
    mov  eax, 0;

    rloop:
        chstop eax;
        chwave eax, 0;
        chpitch eax,0;
        chvolume eax, 0.5;
        chstart eax;

        inc eax;
    loop rloop;
main:
    // Check if playback is still active
    mov eax, #500;
    cmp eax, 0;
    je reset;
    // Check if it's the end of the song
    mov ebx, #memPos
    cmp ebx, eax;
    jg reset;
    // Check if next note should be played
    timer eax;
    sub eax, #startTime;
    cmp eax, #nextTime;
    jl main;

    mov eax, #memPos;

    mov ebx, eax:#1; // channel
    mov ecx, eax:#2; // pitch

    chpitch ebx,ecx;
    chstart ebx;
    mov #nextTime, eax:#3;
    add #memPos, 3;    
jmp main;

// Data
alloc nextTime;
alloc startTime;
alloc memPos;
trackwave: db 'synth/sine_880.wav',0;
//trackwave: db 'synth/white_noise.wav',0;


```
### E2 Code

```
@name midi_dump_reader
@persist SPU:wirelink State:number FileStr:string MemCount:number MemValues:array MemPos:number
@trigger 
if(first()){
    runOnFile(1)
    runOnTick(1)
    setName("")
    SPU = entity():isConstrainedTo():wirelink()
    if(!SPU | SPU:entity():type() != "gmod_wire_spu" ){error("Error: Spawn E2 on SPU! Spawned on "+SPU:entity():type())}
    SPU["Clk",number]=1
    SPU[500]=0
    MemPos = 501
    fileLoad("midi_dump.txt")
}
if(fileClk()){
    FileStr = fileRead()
    MemValues = FileStr:explode(",")
    MemCount = MemValues:count()
    print("Loaded dump file with "+FileStr:length()+" bytes! Total "+MemCount+" memory values.")
    State = 1
}
if(State == 1){
    while(perf()){
        if(MemValues:count()>0){
            SPU[MemPos] = MemValues:shiftString():toNumber()
            MemPos++
        }else{
            SPU[500]=500+MemCount
            print("Dump parsed and loaded!")
            State = 2
            break
        }
    }
}
```
### midi_dump.txt

http://pastebin.com/gKW4cWQV
### midi

http://www.angelfire.com/fl/herky/images/teddybear.mid

**Comment by AbigailBuccaneer** [comment] 2015-01-23 11:56
Quite possibly related to Facepunch/garrysmod-issues#1752.

But it would be a lot more helpful if you could provide a simple test SPU (eg. that just beeps repeatedly) than compiled code plus E2 code plus SPU code.

**Comment by edgarasf123** [comment] 2015-01-23 19:12
I couldn't replicate the issue with beeps. And could the reason be how the sound entities are placed in spu?
![](https://dl.dropboxusercontent.com/u/8081284/ShareX/2015/01/2015-01-23_11-08-07.png)

**Comment by Divran** [comment] 2015-01-23 20:28
I'm blaming the source engine

**Comment by edgarasf123** [comment] 2015-01-25 06:45
Managed to replicate with beeps, there http://bit.ly/1L7qqaK .
```
mov  ecx, 32;
mov  eax, 0;

rloop:
    chstop eax;
    chwave eax, 0;
    chpitch eax,0;
    chvolume eax, 0.5;
    chstart eax;
    
    inc eax;
loop rloop;

main:
    timer eax;
    mov ebx, nextTickTime;
    
    cmp eax, ebx;
    jl main;
    
    add eax, 0.3;
    mov nextTickTime, eax;
    
    mov eax, currentTick;
    mov es, track1;
    chpitch 0,es:#eax;
    chstart 0;
    
    mov es, track2;
    chpitch 1,es:#eax;
    chstart 1;
    
    mov es, track3;
    chpitch 2,es:#eax;
    chstart 2;
    
    mov es, track4;
    chpitch 3,es:#eax;
    chstart 3;
    
    add currentTick, 1;
    mod currentTick, 4;
jmp main;

float currentTick,nextTickTime;

track1: db 0.5,0.5,0.5,0
track2: db 0.9,0.9,0.9,0
track3: db 1.0,0,1.0,1.0
track4: db 1.4,0,1.4,1.4
```

**Comment by edgarasf123** [comment] 2015-01-28 00:27
Found better combination:
```
track1: db 0.0,0.0,0.0,0.5
track2: db 0.0,0.0,1.0,0.0
track3: db 0.0,2.0,0.0,0.0
track4: db 3.0,0.0,0.0,0.0
```
Looks like it would only play random 3 channels, not sure if it's 100% source fault.

**Comment by edgarasf123** [comment] 2015-07-28 20:43
Can't you replace ![CreateSound](https://github.com/wiremod/wire/blob/082a58dd176e7e51c8a7a2f0a079e48917ffb132/lua/entities/gmod_wire_spu/cl_spuvm.lua#L168) with ![sound.PlayFile](http://wiki.garrysmod.com/page/sound/PlayFile)? You can't parent it to an entity, but It does 3D feature. Using ![ENT:CalcAbsolutePosition](http://wiki.garrysmod.com/page/ENTITY/CalcAbsolutePosition) hook to set sound position shouldn't effect the performance too much. And would most likely fix this major issue.

**Comment by thegrb93** [comment] 2015-07-28 21:53
FYI CreateSound has a new channel parameter that should be used. http://wiki.garrysmod.com/page/Global/CreateSound

**Comment by Divran** [comment] 2015-07-28 22:01
if anyone wants to make pull request that'd be great

**Comment by edgarasf123** [comment] 2015-07-28 23:25
@thegrb93 
![](http://i.imgur.com/oYocdsY.png)
The channel parameter has default parameter, so each sound entity should already have their own channels.

**Comment by edgarasf123** [comment] 2015-07-29 02:44
It does work, made quick code to test it. 
Here, same midi code played using sound.PlayFile
 https://copy.com/HsvwabhdPFsq/2015-07-28_19-28-12.mp4

I wrote a small hack to get rid of the callback using metatables. It's really unstable, if SPU poorly written, it will freeze your game. And I don't really want to mess with the SPU internal code. I would appreciate if someone could implement this correctly.
 [cl_spuvm.lua](http://pastebin.com/gpeXTqsR)

**Comment by thegrb93** [comment] 2015-07-29 17:57
@edgarasf123 What I meant is you should use one targetEnt and use different channels rather than a bunch of targetEnt using one channel.

**Comment by edgarasf123** [comment] 2015-07-29 18:53
@thegrb93 They already do use their own channel.

**Comment by thegrb93** [comment] 2015-07-29 19:28
*facepalm* Please read more closely. Each single channel is using a prop_physics to convey the sound. Instead, solely the spu itself should CreateSound, but use different channels for the sounds.

**Comment by edgarasf123** [comment] 2015-07-30 01:16
I understand. But is it going to fix this issue? And messing with the channels could cause other issues. For example SPU entity id is 121 and it creates sound channels [121...129], then someone places an E2(which also plays sounds) and its entity id is assigned to 122, then there will be 2 entities playing on a single channel.

**Comment by TomyLobo** [comment] 2015-07-30 06:02
@edgarasf123 when playing midi, you need more than one channel **per** entity

**Comment by edgarasf123** [comment] 2015-07-30 06:37
@TomyLobo SPU does right now create 32 entities for each sound channel. The issue is that the source engine is not able to play multiple channels at once (3 at most). That's why I'm suggesting to switch [CreateSound](http://wiki.garrysmod.com/page/Global/CreateSound) to [sound.PlayFile](http://wiki.garrysmod.com/page/sound/PlayFile), which uses [BASS audio library](http://www.un4seen.com/) and it's able to play multiple channels at once just fine.

EID*10+Index doesn't stop you from getting the issue I described above. 

The channel parameter is pointless. Because by changing channel id, you're just going to mess with random entity sound channel. The only place is see this parameter could be used is in custom gamemode, where the developer has full control over environment,

**Comment by thegrb93** [comment] 2015-07-30 14:22
Then yes, BASS is the best option. Last time I tried BASS though, it was unable to play wav loops. Don't know if that is fixed yet or not.

**Comment by edgarasf123** [comment] 2015-07-30 14:49
You have to add noplay flag.

**Comment by thegrb93** [comment] 2015-07-30 16:07
That fixes the BASS_ERROR_UNKNOWN?

**Comment by TomyLobo** [comment] 2015-07-30 16:28
@edgarasf123 Didn't you say you can't parent sound.PlayFile to an entity?
Isn't that bad if your SPU is moving?

**Comment by edgarasf123** [comment] 2015-07-30 17:15
That's why I said to use [ENT:CalcAbsolutePosition](http://wiki.garrysmod.com/page/ENTITY/CalcAbsolutePosition) hook, to update the location of sound.

**Comment by edgarasf123** [comment] 2015-07-30 17:23
@thegrb93 I didn't get BASS_ERROR_UNKNOWN error at all. The only issue I got initially is that looping sounds such as "synth/sine.wav" would only play for half a second. Adding "noplay" flag fixed the issue.

**Comment by thegrb93** [comment] 2015-07-30 19:02
Ah here, I found the issue https://github.com/wiremod/wire/issues/794

**Comment by TomyLobo** [comment] 2015-08-01 05:33
@edgarasf123 
So you change the sound position once a frame, via Lua.
Isn't that terribly inefficient?

**Comment by thegrb93** [comment] 2015-08-01 06:36
No

**Comment by TomyLobo** [comment] 2015-08-01 10:37
just "No"?

**Comment by thegrb93** [comment] 2015-08-01 11:32
Why would changing the position of a sound be inefficient?

**Comment by TomyLobo** [comment] 2015-08-01 16:07
you're doing that every single frame for every SPU for every sound

**Comment by edgarasf123** [comment] 2015-08-01 16:38
It's clientside, so it won't slutter back and forth.

**Comment by Divran** [comment] 2015-08-01 17:32
Someone just try it instead of arguing then

**Comment by oldmud0** [comment] 2015-08-01 18:55
Isn't Source mostly single threaded?

**Comment by thegrb93** [comment] 2015-08-02 00:01
@oldmud0 If it was expensive then yes, but setting a position is not expensive.

**Comment by TomyLobo** [comment] 2015-08-02 07:31
it could bring performance down by pure virtue of being single-threaded

**Comment by Divran** [comment] 2015-08-02 10:22
@thegrb93 setting the position of entities is quite expensive in the source engine. That's why I made all projectiles clientside in pewpew, to spam entity position there instead of on the server. This doesn't necessarily mean that setting the position of sounds in the way we're talking about here is also expensive, but you can't say that setting ANY position is inexpensive, because that's not true.

Now, everyone, shut the hell up until one of you actually tries it

**Comment by thegrb93** [comment] 2015-08-02 10:40
Yeah, what I meant was setting positions of the sounds.

**Comment by edgarasf123** [comment] 2015-11-24 15:54
Was it fixed?

**Comment by AbigailBuccaneer** [comment] 2015-11-24 16:41
@immibis apparently your change doesn't work in all situations.

**Comment by immibis** [comment] 2015-11-24 19:31
@edgarasf123 It seemed to work for me, at least back in April when I made that PR. Does it behave differently at all (with the sound sources at the same position)?

**Comment by fuadxtps23** [comment] 2022-12-14 13:38
anyone know, what must i use for sound output for spu

**Closed** 2023-06-12 16:50 UTC
Labels: Bug, ZCPU
