### ISSUE TITLE
ZCPU stack problems with address bus RAM

### ISSUE THREAD

**Issue by VigilanteHobo** [wiremod/wire#2044] opened 2020-04-12 20:08 UTC
The stack pointer (ESP) is automatically set to zero when using external ram and when set to 32767 the values are offset by one, presumably because the stack will use the total size of the ram.

**Comment by Zer0Notha** [comment] 2020-04-13 10:57
This is not a bug, please read the documentation carefully
There are 3 registers to stack control: SS - Stack Segment, ESP - Stack Pointer, ESZ - Stack Size
Stack pointer must be less or equal to stack size for logical reasons ( ESP ⩽ ESZ )
So you must set ESZ to higher values to use external RAM like stack
```
mov ESP, 524288 //512kb
cpuset 9, 524288 //512kb
push EAX
pop EAX
```
But I recommend using a stack segment for this to avoid errors when the stack hits the code
```
mov SS, 524288 //now adress of stack is SS+ESP and stack size is ESZ
push EAX
pop EAX
```
![image](https://user-images.githubusercontent.com/53031298/79115444-86494c00-7d8e-11ea-8d85-bb522deba420.png)
![image](https://user-images.githubusercontent.com/53031298/79115483-9bbe7600-7d8e-11ea-8e88-e680948aabdf.png)
![image](https://user-images.githubusercontent.com/53031298/79115509-af69dc80-7d8e-11ea-9da0-3eff658ba416.png)

**Comment by thegrb93** [comment] 2020-04-13 11:14
Thanks for the explanation. If VigilanteHobo agrees then we can close it.

**Comment by VigilanteHobo** [comment] 2020-04-13 12:40
Ill check real quick to see if this works.

**Comment by VigilanteHobo** [comment] 2020-04-13 12:45
Works as expected after applying the patch. Thank you for your help.

**Comment by Zer0Notha** [comment] 2020-04-13 12:57
> Works as expected after applying the patch. Thank you for your help.

You're welcome. [There](https://github.com/wiremod/Miscellaneous/blob/master/CPU%20%26%20GPU/zcpudocs/zcpudoc.pdf) is outdated documentation for ZCPU/GPU, in most cases it is working
Also you can ask me directly in the [steam](https://steamcommunity.com/id/KillerFake2/)

**Closed** 2020-04-13 13:04 UTC
Labels: Not a bug, ZCPU
