### ISSUE TITLE
Making two ranger lasers touch each other crashes the server

### ISSUE THREAD

**Issue by RhapsodySL** [wiremod/wire#863] opened 2015-03-12 01:03 UTC
Making two ranger lasers touch the opposing ranger instantly crashes the server without fail. While the prospect is sort of kinky, it's pretty dangerous and probably works with other tools that use those beams as well.

**Comment by Divran** [comment] 2015-03-12 18:05
what?

**Comment by RhapsodySL** [comment] 2015-03-12 18:06
Exactly what it sounds like. The beam that comes  from a ranger crashes the server if it touches another ranger.

**Comment by Divran** [comment] 2015-03-12 18:07
I just tested that and nothing happened

**Comment by RhapsodySL** [comment] 2015-03-12 18:07
If it helps, I'm doing this on DarkRP 2.6.0 with a fresh copy from the wire github.

**Comment by FPtje** [comment] 2015-03-12 18:47
![countexample](Making two ranger lasers touch the opposing ranger)
It's not DarkRP

**Comment by thegrb93** [comment] 2015-03-12 22:38
DONT CROSS THE BEAMS

**Comment by thegrb93** [comment] 2015-03-12 22:39
What settings do you have checked in the ranger menu?

**Comment by Nebual** [comment] 2015-03-13 05:32
I've never heard of this from beams, can't reproduce it, nor does it make a whole lot of sense since as Divran said the beam is just a visual material being drawn between two vectors + a traceline. 

Closing as unreproducable on Wiremod's end.

This seems like a pretty funny case, so I'd like to see it if you'll accept my Steam invite.

**Closed by Nebual** 2015-03-13 05:32 UTC
Labels: Bug, Crash

**Comment by RhapsodySL** [comment] 2015-03-13 13:50
Will do, and I'll try to capture some footage of the issue next time I jump onto my computer.
