### ISSUE TITLE
Backward compatibility when declaring a function

### ISSUE THREAD

**Issue by foul11** [wiremod/wire#2882] opened 2023-11-19 21:53 UTC
Old code

```lua
function number f(){
    if(1){
        return 1
    }
}
```

**Before**: Validation successful.
**Now**: Error (1/1): This function marked to return 'number' must return a value.

**Comment by foul11** [comment] 2023-11-19 22:03
This code also stopped compiling:

```lua
function number f(){
    return ("")()[table]:exists("")
}

# -- Error (1/1): Statements must be separated by comma (,) or whitespace
```

This code return internal error

```lua
return ("")()

#[--[[
Trace:
	1: Line 32	"Trace"		lua/includes/extensions/debug.lua
	2: Line 336	"__index"		lua/entities/gmod_wire_expression2/core/e2lib.lua
	3: Line 320	"Stmt"		lua/entities/gmod_wire_expression2/base/parser.lua
	4: Line 188	"nil"		lua/entities/gmod_wire_expression2/base/parser.lua
	5: C function	"xpcall"
	6: Line 133	"Execute"		lua/entities/gmod_wire_expression2/base/parser.lua
	7: Line 73	"Validate"		lua/entities/gmod_wire_expression2/cl_init.lua
	8: Line 1429	"Validate"		lua/wire/client/text_editor/wire_expression2_editor.lua
	9: Line 792	"OnMousePressed"		lua/wire/client/text_editor/wire_expression2_editor.lua
	10: Line 151	"nil"		lua/wire/client/text_editor/issue_viewer.lua
--]] ]#
```

This code was evaluated at runtime and therefore did not generate errors if the function was redefined.
This was used at the top of the code because there is no function bubbling in e2.
```lua
if(1){
    function table some(){}
}

# -- Error (1/1): This function marked to return 'table' must return a value
```

**Comment by Denneisk** [comment] 2023-11-19 23:35
> ```lua
> function number f(){
>     if(1){
>         return 1
>     }
> }
> ```

E2 can't infer for cases like that. You'll have to put a return at the end with a default value. Maybe in the future but it's a bad practice if in the future for whatever reason that if condition is no longer true.

> ```lua
> return ("")()[table]:exists("")
> ```

Is there a purpose to trying to call an unnamed function besides trying to break E2? Either way, the issue is that you need to enclose the function call with its return type in one. Don't know if that's a regression or not @Vurv78.

> ```lua
> if(1){
>    function table some(){}
> }
> ```

The condition doesn't matter, the function doesn't return so it's erroring. Functions are compile-time now. See [lambdas](/wiremod/wire/wiki/Expression-2-Syntax#lambda-functions) for a dynamic replacement.

**Comment by Vurv78** [comment] 2023-11-20 00:53
> Old code
> 
> ```lua
> function number f(){
>     if(1){
>         return 1
>     }
> }
> ```
> 
> **Before**: Validation successful. **Now**: Error (1/1): This function marked to return 'number' must return a value.

Now after realizing how many people have improperly defined their functions or abused empty functions for overriding, the plan was to revert this behavior for non-`@strict`

Also non backwards compatibility wise, that code should compile error. In the future maybe the optimizer would eliminate that if statement, but this is just some crafted code that would crash the chip. You can still use switch and if at the end of a function, as long as all cases return.

**Comment by AlexALX** [comment] 2024-03-28 16:00
> Now after realizing how many people have improperly defined their functions or abused empty functions for overriding, the plan was to revert this behavior and make it a warning for non-`@strict`

any news on that? since my pc still broken because of that and seems way much to fix. if its not going to be reverted then can just remove it from workshop.

**Comment by thegrb93** [comment] 2024-03-28 16:40
It's not way much to fix

**Comment by thegrb93** [comment] 2024-03-28 16:42
Closing since it doesn't seem like a regression. Just a slightly stricter standard

**Closed by thegrb93** 2024-03-28 16:42 UTC
Labels: E2
