### ISSUE TITLE
Memory=>String doesnt have inputs

### ISSUE THREAD

**Issue by micheel665** [wiremod/wire#919] opened 2015-07-04 16:25 UTC
in gates/string
String=>Memory takes a string and outputs memory
but
Memory=>String takes no values and outputs memory and string

**Comment by Divran** [comment] 2015-07-04 18:43
That's because you're meant to use wirelinks to talk to it

**Comment by TomyLobo** [comment] 2015-07-04 19:10
iirc, the "memory" output is so you can wire it up to a Wire CPU, which doesn't support wirelink but rather hacks itself through the wirelib to obtain a handle on the target's memory

**Comment by Divran** [comment] 2015-07-04 20:09
Yeah memory outputs are sort of CPU's wirelinks

**Comment by micheel665** [comment] 2015-07-05 09:50
yha but what if I want to take a string, convert it to memory, store it in a ram gate, take it out of the ram gate and then convert it to a string again?

**Comment by Divran** [comment] 2015-07-05 10:16
I believe the ram gate is for cpu, so then you'd use cpu to do it. There are other ways of storing data if you don't want to use cpu, like the dhdd for example.

**Comment by micheel665** [comment] 2015-07-05 10:48
ok thanks for the info

**Comment by oldmud0** [comment] 2015-07-05 23:28
Now the issue is just closing the issue.

**Closed** 2015-07-06 06:48 UTC

**Comment by TomyLobo** [comment] 2015-07-06 07:06
gesundheit
